project:
  type: website

website:
  title: "Box Office Numbers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: budget-revenue.qmd
        text: Budget and Revenue
      - href: runtime-rating.qmd
        text: Runtime and Ratings
      - href: bond.qmd
        text: The Bond Films

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto


